In [1]:
import numpy as np

### Creating the adjacency matrix

In [2]:
np.random.seed(42)
N = 6
# random upper triangle of matrix (0/1 connections)
upper = np.random.randint(0, 2, size=(N, N))
A = np.triu(upper, 1)  # keep only upper triangle, remove diagonal
A = A + A.T            # make it symmetric
print("Adjacency matrix A:\n", A)

Adjacency matrix A:
 [[0 1 0 0 0 1]
 [1 0 0 1 0 0]
 [0 0 0 0 1 1]
 [0 1 0 0 1 1]
 [0 0 1 1 0 1]
 [1 0 1 1 1 0]]


### Vertex degrees

In [3]:
degrees = A.sum(axis=1)
print("Degrees:", degrees)

max_user = np.argmax(degrees)
print("User with most connections:", max_user, "with degree", degrees[max_user])


Degrees: [2 2 2 3 3 4]
User with most connections: 5 with degree 4


### Matrix of paths of length 2

In [4]:
A2 = np.dot(A, A)
print("A^2:\n", A2)

A^2:
 [[2 0 1 2 1 0]
 [0 2 0 0 1 2]
 [1 0 2 2 1 1]
 [2 0 2 3 1 1]
 [1 1 1 1 3 2]
 [0 2 1 1 2 4]]


### Indirect friends (friends-of-friends)

In [5]:
# Boolean mask of reachable in 2 steps
friends_of_friends = (A2 > 0)

# remove direct friends and self
indirect = friends_of_friends & (A == 0) & (~np.eye(N, dtype=bool))
counts_indirect = indirect.sum(axis=1)
print("Indirect friends count:", counts_indirect)

Indirect friends count: [3 2 2 2 2 1]


### Eigenvalues & Spectral Radius

In [6]:
eigvals = np.linalg.eigvals(A)
spectral_radius = np.max(np.abs(eigvals))

print("Eigenvalues:", eigvals)
print("Spectral radius:", spectral_radius)

Eigenvalues: [ 2.85291736  1.05542279 -2.15843759  0.18300709 -1.2718488  -0.66106085]
Spectral radius: 2.852917361961511
